name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisites
      run: |
        sudo apt install -y libzmq3-dev libsqlite3-dev libssl-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python packages
      run: |
        pip install pip --upgrade
        pip install -r requirements.txt
    - name: Run tests
      run: |
        ./run_tests.sh
    - name: Run bdd tests
      run: |
        ./run_bdd_tests.sh
